# Generated by Django 5.2.1 on 2025-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проектов')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('tehnology_project', models.TextField(default='Технологии не указаны', verbose_name='Технологии проекта')),
                ('image', models.ImageField(default='products/default_image.jpg', upload_to='products/')),
                ('link', models.URLField(max_length=500, verbose_name='Ссылка на проект')),
            ],
        ),
    ]
